micronaut:
  application:
    name: appointmentalert
  security:
    authentication: bearer
    endpoints:
      login:
        path: /api/login
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SECRET:supersecretsupersecretsupersecretsupersecret}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
jackson:
  date-format: "yyyy-MM-dd"
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: CREATE
    dialect: MYSQL
    jdbc-url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:appointmentalert}?user=${DB_USER:appointmentalert}&password=${DB_PASSWORD:supersecret}
netty:
  default:
    allocator:
      max-order: 3
